
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.3 EDK_O.76xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_XPS_GPIO_1_DEVICE_ID,
		XPAR_XPS_GPIO_1_BASEADDR,
		XPAR_XPS_GPIO_1_INTERRUPT_PRESENT,
		XPAR_XPS_GPIO_1_IS_DUAL
	}
};


