
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.3 EDK_O.76xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xbram.h"

/*
* The configuration table for devices
*/

XBram_Config XBram_ConfigTable[] =
{
	{
		XPAR_XPS_BRAM_IF_CNTLR_0_DEVICE_ID,
		XPAR_XPS_BRAM_IF_CNTLR_0_DATA_WIDTH,
		XPAR_XPS_BRAM_IF_CNTLR_0_ECC,
		XPAR_XPS_BRAM_IF_CNTLR_0_FAULT_INJECT,
		XPAR_XPS_BRAM_IF_CNTLR_0_CE_FAILING_REGISTERS,
		XPAR_XPS_BRAM_IF_CNTLR_0_UE_FAILING_REGISTERS,
		XPAR_XPS_BRAM_IF_CNTLR_0_ECC_STATUS_REGISTERS,
		XPAR_XPS_BRAM_IF_CNTLR_0_CE_COUNTER_WIDTH,
		XPAR_XPS_BRAM_IF_CNTLR_0_ECC_ONOFF_REGISTER,
		XPAR_XPS_BRAM_IF_CNTLR_0_ECC_ONOFF_RESET_VALUE,
		XPAR_XPS_BRAM_IF_CNTLR_0_WRITE_ACCESS,
		XPAR_XPS_BRAM_IF_CNTLR_0_BASEADDR,
		XPAR_XPS_BRAM_IF_CNTLR_0_HIGHADDR
	}
};


