
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 13.3 EDK_O.76xd
* DO NOT EDIT.
*
* Copyright (c) 1995-2011 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver parameters
*
*******************************************************************/

#define STDIN_BASEADDRESS 0x84400000
#define STDOUT_BASEADDRESS 0x84400000

/******************************************************************/

/* Definitions for driver UARTLITE */
#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral DEBUG_MODULE_0 */
#define XPAR_DEBUG_MODULE_0_BASEADDR 0x84400000
#define XPAR_DEBUG_MODULE_0_HIGHADDR 0x8440FFFF
#define XPAR_DEBUG_MODULE_0_DEVICE_ID 0
#define XPAR_DEBUG_MODULE_0_BAUDRATE 0
#define XPAR_DEBUG_MODULE_0_USE_PARITY 0
#define XPAR_DEBUG_MODULE_0_ODD_PARITY 0
#define XPAR_DEBUG_MODULE_0_DATA_BITS 0


/******************************************************************/

/* Canonical definitions for peripheral DEBUG_MODULE_0 */
#define XPAR_UARTLITE_0_DEVICE_ID XPAR_DEBUG_MODULE_0_DEVICE_ID
#define XPAR_UARTLITE_0_BASEADDR 0x84400000
#define XPAR_UARTLITE_0_HIGHADDR 0x8440FFFF
#define XPAR_UARTLITE_0_BAUDRATE 0
#define XPAR_UARTLITE_0_USE_PARITY 0
#define XPAR_UARTLITE_0_ODD_PARITY 0
#define XPAR_UARTLITE_0_DATA_BITS 0
#define XPAR_UARTLITE_0_SIO_CHAN -1


/******************************************************************/

/* Definitions for driver MPMC */
#define XPAR_XMPMC_NUM_INSTANCES 1

/* Definitions for peripheral MPMC_0 */
#define XPAR_MPMC_0_DEVICE_ID 0
#define XPAR_MPMC_0_MPMC_CTRL_BASEADDR 0x84800000
#define XPAR_MPMC_0_INCLUDE_ECC_SUPPORT 0
#define XPAR_MPMC_0_USE_STATIC_PHY 1
#define XPAR_MPMC_0_PM_ENABLE 0
#define XPAR_MPMC_0_NUM_PORTS 2
#define XPAR_MPMC_0_MEM_DATA_WIDTH 32
#define XPAR_MPMC_0_MEM_PART_NUM_BANK_BITS 2
#define XPAR_MPMC_0_MEM_PART_NUM_ROW_BITS 12
#define XPAR_MPMC_0_MEM_PART_NUM_COL_BITS 9
#define XPAR_MPMC_0_MEM_TYPE SDRAM
#define XPAR_MPMC_0_ECC_SEC_THRESHOLD 1
#define XPAR_MPMC_0_ECC_DEC_THRESHOLD 1
#define XPAR_MPMC_0_ECC_PEC_THRESHOLD 1
#define XPAR_MPMC_0_MEM_DQS_WIDTH 4
#define XPAR_MPMC_0_MPMC_CLK0_PERIOD_PS 10000


/******************************************************************/


/* Definitions for peripheral MPMC_0 */
#define XPAR_MPMC_0_MPMC_BASEADDR 0x00000000
#define XPAR_MPMC_0_MPMC_HIGHADDR 0x01FFFFFF
#define XPAR_MPMC_0_MPMC_CTRL_BASEADDR 0x84800000
#define XPAR_MPMC_0_MPMC_CTRL_HIGHADDR 0x8480FFFF
#define XPAR_MPMC_0_BASEADDR_CTRL0 0x000
#define XPAR_MPMC_0_HIGHADDR_CTRL0 0x00c
#define XPAR_MPMC_0_BASEADDR_CTRL2 0x016
#define XPAR_MPMC_0_HIGHADDR_CTRL2 0x022
#define XPAR_MPMC_0_BASEADDR_CTRL3 0x023
#define XPAR_MPMC_0_HIGHADDR_CTRL3 0x02b
#define XPAR_MPMC_0_BASEADDR_CTRL4 0x02c
#define XPAR_MPMC_0_HIGHADDR_CTRL4 0x038
#define XPAR_MPMC_0_BASEADDR_CTRL5 0x039
#define XPAR_MPMC_0_HIGHADDR_CTRL5 0x041
#define XPAR_MPMC_0_BASEADDR_CTRL6 0x042
#define XPAR_MPMC_0_HIGHADDR_CTRL6 0x052
#define XPAR_MPMC_0_BASEADDR_CTRL7 0x053
#define XPAR_MPMC_0_HIGHADDR_CTRL7 0x05f
#define XPAR_MPMC_0_BASEADDR_CTRL8 0x060
#define XPAR_MPMC_0_HIGHADDR_CTRL8 0x078
#define XPAR_MPMC_0_BASEADDR_CTRL9 0x079
#define XPAR_MPMC_0_HIGHADDR_CTRL9 0x08d
#define XPAR_MPMC_0_BASEADDR_CTRL10 0x08e
#define XPAR_MPMC_0_HIGHADDR_CTRL10 0x09e
#define XPAR_MPMC_0_BASEADDR_CTRL11 0x09f
#define XPAR_MPMC_0_HIGHADDR_CTRL11 0x0ab
#define XPAR_MPMC_0_BASEADDR_CTRL12 0x0ac
#define XPAR_MPMC_0_HIGHADDR_CTRL12 0x0bc
#define XPAR_MPMC_0_BASEADDR_CTRL13 0x0bd
#define XPAR_MPMC_0_HIGHADDR_CTRL13 0x0c9
#define XPAR_MPMC_0_BASEADDR_CTRL14 0x0ca
#define XPAR_MPMC_0_HIGHADDR_CTRL14 0x0d3
#define XPAR_MPMC_0_BASEADDR_CTRL15 0x0d4
#define XPAR_MPMC_0_HIGHADDR_CTRL15 0x0d5
#define XPAR_MPMC_0_BASEADDR_CTRL16 0x0d9
#define XPAR_MPMC_0_HIGHADDR_CTRL16 0x0da


/******************************************************************/


/******************************************************************/


/* Definitions for peripheral PLB_USB_0 */
#define XPAR_PLB_USB_0_BASEADDR 0xC9C00000
#define XPAR_PLB_USB_0_HIGHADDR 0xC9C0FFFF


/* Definitions for peripheral PLB_VISION_0 */
#define XPAR_PLB_VISION_0_BASEADDR 0xC4600000
#define XPAR_PLB_VISION_0_HIGHADDR 0xC460FFFF


/******************************************************************/

/* Definitions for driver BRAM */
#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral XPS_BRAM_IF_CNTLR_1 */
#define XPAR_XPS_BRAM_IF_CNTLR_1_DEVICE_ID 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_DATA_WIDTH 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_FAULT_INJECT 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_CE_FAILING_REGISTERS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_UE_FAILING_REGISTERS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC_STATUS_REGISTERS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_CE_COUNTER_WIDTH 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC_ONOFF_REGISTER 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_ECC_ONOFF_RESET_VALUE 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_WRITE_ACCESS 0
#define XPAR_XPS_BRAM_IF_CNTLR_1_BASEADDR 0xFFFE0000
#define XPAR_XPS_BRAM_IF_CNTLR_1_HIGHADDR 0xFFFFFFFF


/******************************************************************/

/* Canonical definitions for peripheral XPS_BRAM_IF_CNTLR_1 */
#define XPAR_BRAM_0_DEVICE_ID XPAR_XPS_BRAM_IF_CNTLR_1_DEVICE_ID
#define XPAR_BRAM_0_DATA_WIDTH 0
#define XPAR_BRAM_0_ECC 0
#define XPAR_BRAM_0_FAULT_INJECT 0
#define XPAR_BRAM_0_CE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_UE_FAILING_REGISTERS 0
#define XPAR_BRAM_0_ECC_STATUS_REGISTERS 0
#define XPAR_BRAM_0_CE_COUNTER_WIDTH 0
#define XPAR_BRAM_0_ECC_ONOFF_REGISTER 0
#define XPAR_BRAM_0_ECC_ONOFF_RESET_VALUE 0
#define XPAR_BRAM_0_WRITE_ACCESS 0
#define XPAR_BRAM_0_BASEADDR 0xFFFE0000
#define XPAR_BRAM_0_HIGHADDR 0xFFFFFFFF


/******************************************************************/

#define XPAR_INTC_MAX_NUM_INTR_INPUTS 2
#define XPAR_XINTC_HAS_IPR 1
#define XPAR_XINTC_HAS_SIE 1
#define XPAR_XINTC_HAS_CIE 1
#define XPAR_XINTC_HAS_IVR 1
#define XPAR_XINTC_USE_DCR 0
/* Definitions for driver INTC */
#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral XPS_INTC_1 */
#define XPAR_XPS_INTC_1_DEVICE_ID 0
#define XPAR_XPS_INTC_1_BASEADDR 0x81400000
#define XPAR_XPS_INTC_1_HIGHADDR 0x8140FFFF
#define XPAR_XPS_INTC_1_KIND_OF_INTR 0xFFFFFFFD


/******************************************************************/

#define XPAR_INTC_SINGLE_BASEADDR 0x81400000
#define XPAR_INTC_SINGLE_HIGHADDR 0x8140FFFF
#define XPAR_INTC_SINGLE_DEVICE_ID XPAR_XPS_INTC_1_DEVICE_ID
#define XPAR_PLB_VISION_0_INTERRUPT_MASK 0X000001
#define XPAR_XPS_INTC_1_PLB_VISION_0_INTERRUPT_INTR 0
#define XPAR_PLB_USB_0_INTERRUPT_MASK 0X000002
#define XPAR_XPS_INTC_1_PLB_USB_0_INTERRUPT_INTR 1

/******************************************************************/

/* Canonical definitions for peripheral XPS_INTC_1 */
#define XPAR_INTC_0_DEVICE_ID XPAR_XPS_INTC_1_DEVICE_ID
#define XPAR_INTC_0_BASEADDR 0x81400000
#define XPAR_INTC_0_HIGHADDR 0x8140FFFF
#define XPAR_INTC_0_KIND_OF_INTR 0xFFFFFFFD


/******************************************************************/


/* Definitions for peripheral XPS_MCH_EMC_SRAM */
#define XPAR_XPS_MCH_EMC_SRAM_NUM_BANKS_MEM 1


/******************************************************************/

/* Definitions for peripheral XPS_MCH_EMC_SRAM */
#define XPAR_XPS_MCH_EMC_SRAM_MEM0_BASEADDR 0x81D00000
#define XPAR_XPS_MCH_EMC_SRAM_MEM0_HIGHADDR 0x81DFFFFF

/******************************************************************/

/* Canonical definitions for peripheral XPS_MCH_EMC_SRAM */
#define XPAR_EMC_0_NUM_BANKS_MEM 1
#define XPAR_EMC_0_MEM0_BASEADDR 0x81D00000
#define XPAR_EMC_0_MEM0_HIGHADDR 0x81DFFFFF

#define XPAR_XPS_MCH_EMC

/******************************************************************/

/* Definition for PPC cacheable regions */
#define XPAR_CACHEABLE_REGION_MASK 0x80008001
/******************************************************************/

/* Definitions for bus frequencies */
#define XPAR_CPU_PPC405_DPLB0_FREQ_HZ 100000000
#define XPAR_CPU_PPC405_IPLB0_FREQ_HZ 100000000
/******************************************************************/

/* Canonical definitions for bus frequencies */
#define XPAR_PROC_BUS_0_FREQ_HZ 100000000
/******************************************************************/

#define XPAR_CPU_PPC405_CORE_CLOCK_FREQ_HZ 300000000
#define XPAR_PPC405_VIRTEX4_CORE_CLOCK_FREQ_HZ 300000000

/******************************************************************/

#define XPAR_CPU_ID 1
#define XPAR_PPC405_VIRTEX4_ID 1
#define XPAR_PPC405_VIRTEX4_DPLB0_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB0_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB0_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB1_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB1_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_IPLB1_NATIVE_DWIDTH 64
#define XPAR_PPC405_VIRTEX4_DPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_VIRTEX4_DPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_VIRTEX4_IPLB1_ADDR_BASE 0xffffffff
#define XPAR_PPC405_VIRTEX4_IPLB1_ADDR_HIGH 0x00000000
#define XPAR_PPC405_VIRTEX4_FASTEST_PLB_CLOCK DPLB0
#define XPAR_PPC405_VIRTEX4_GENERATE_PLB_TIMESPECS 1
#define XPAR_PPC405_VIRTEX4_DPLB0_P2P 0
#define XPAR_PPC405_VIRTEX4_DPLB1_P2P 1
#define XPAR_PPC405_VIRTEX4_IPLB0_P2P 0
#define XPAR_PPC405_VIRTEX4_IPLB1_P2P 1
#define XPAR_PPC405_VIRTEX4_IDCR_BASEADDR 0x00000100
#define XPAR_PPC405_VIRTEX4_IDCR_HIGHADDR 0x000001FF
#define XPAR_PPC405_VIRTEX4_DISABLE_OPERAND_FORWARDING 1
#define XPAR_PPC405_VIRTEX4_MMU_ENABLE 1
#define XPAR_PPC405_VIRTEX4_DETERMINISTIC_MULT 0
#define XPAR_PPC405_VIRTEX4_PLBSYNCBYPASS 1
#define XPAR_PPC405_VIRTEX4_APU_CONTROL 0b1101111000000000
#define XPAR_PPC405_VIRTEX4_APU_UDI_1 0b101000011000100110000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_2 0b101000111000100110000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_3 0b101001011000100111000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_4 0b101001111000100111000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_5 0b101010011000110000000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_6 0b101010111000110000000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_7 0b101011011000110001000011
#define XPAR_PPC405_VIRTEX4_APU_UDI_8 0b101011111000110001000011
#define XPAR_PPC405_VIRTEX4_PVR_HIGH 0b0000
#define XPAR_PPC405_VIRTEX4_PVR_LOW 0b0000
#define XPAR_PPC405_VIRTEX4_HW_VER "2.01.b"

/******************************************************************/

